version: '3'
services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile_api
    ports:
      - "8888:3000"
    networks: 
      - syncpimp
    volumes:
#      - "./api/src/src/:/app/src"
      - "/Volumes/CodeProjectsSampleData/fi.wegar.sync-pimp/qsync:/app/data/qsync:ro"
  
  client:
    build: 
      context: .
      dockerfile: Dockerfile_client
    ports:
      - "80:3000"
    networks: 
      - syncpimp
    depends_on: 
      - api
    volumes:
      - "./client/src:/app/src"
      - "./client/public:/app/public"
      - "./client/package.json:/app/package.json"

networks: 
  syncpimp: